Push upstream
infratographer/krakend-endpoints-tool pull request #1
Opened 2023-02-14 17:06 UTC by JAORMX

This pushes all the changes initially done in https://github.com/JAORMX/krakend-endpoints-tool towards infratographer.

2023-02-14 17:58 UTC, JAORMX commented on .github/CODEOWNERS
> +* @infratographer/identity_maintainers
That's a good idea. I can push the change tomorrow

2023-02-15 14:53 UTC, fishnix approved these changes

2023-02-15 14:53 UTC, fishnix commented on main.go
> +Copyright © 2023 Equinix Metal
```suggestion
Copyright © 2023 Infratographer Authors
```

👀

2023-02-15 16:43 UTC, fishnix requested changes

2023-02-15 16:49 UTC, fishnix approved these changes

2023-02-20 11:51 UTC, merged